apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: load-balancer-example
  name: my-service
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 9090
  selector:
    app.kubernetes.io/name: load-balancer-example
  type: ClusterIP
